### Algorithms Final Projects

DARYL WILLIAMS B. BULLECER

### LargestNumber

### TASK

## Example

For `n = 2`, the output should be `largestNumber(n) = 99`.

### Hints
- `concat()`
- `parseInt()`

### Input/Output

- **[execution time limit]** 4 seconds (js)
- **[input]** integer `n`
    - Guaranteed constraints:
      - `1 ≤ n ≤ 9`

- **[output]** integer
    - Guaranteed constraints:
      - The largest integer of length `n`.


## Problem Explanation:

You are tasked with generating the largest integer that has a length of `n` digits. The integer must be made using the largest possible digit, which is `9`.

### Example:
For `n = 2`, the output should be `largestNumber(n) = 99`.

## Approach:
The problem is asking for the largest integer of length `n`. Since the largest digit is `9`, for any `n`, you can simply create a string of `n` nines and then convert it to an integer.

For example:
- If `n = 2`, the largest number is `"99"`.
- If `n = 3`, the largest number is `"999"`.
- If `n = 5`, the largest number is `"99999"`.

This approach works because `9` is the largest possible digit, so the largest number of length `n` is just `n` repeated `9`s.


### ANSWER

In [ ]:
def largestNumber(n):
    # Create a string with 'n' nines and convert it to an integer
    return int('9' * n)

# Example: n = 2
print(largestNumber(2))  # Output: 99

# Example: n = 3
print(largestNumber(3))  # Output: 999

# Example: n = 5
print(largestNumber(5))  # Output: 99999


99
999
99999


## Explanation:

- **`'9' * n`**: This creates a string consisting of `n` repeated characters of `'9'`. For example, if `n = 2`, it will produce the string `"99"`.

- **`int()`**: Converts the string to an integer. For instance, `"99"` becomes `99`.

### Output:
- For `n = 2`, the output will be `99`.
- For `n = 3`, the output will be `999`.
- For `n = 5`, the output will be `99999`.

### Why it works:
Since `9` is the largest single digit, and the number needs to have exactly `n` digits, the largest number of length `n` is simply a string of `n` `'9'` characters.

This Python solution is straightforward and efficient for the given constraints `1 ≤ n ≤ 9`.


### LargestOfFour

### Task

## Problem Statement:

Return an array consisting of the largest number from each provided sub-array. For simplicity, the provided array will contain exactly 4 sub-arrays.

Remember, you can iterate through an array with a simple for loop, and access each member with array syntax `arr[i]`.

### Example:

```javascript
largestOfFour([ [4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])
// returns [5, 27, 39, 1001]

largestOfFour([ [4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]])
// returns [9, 35, 97, 1000000]


### Task:
The task is to find the largest number in each of the four provided sub-arrays and return an array containing those largest values.

### Approach:
1. Iterate over each sub-array in the main array.
2. For each sub-array, find the largest number.
3. Store the largest number from each sub-array.
4. Return an array containing these largest numbers.

### Example:

- For the sub-array `[4, 5, 1, 3]`, the largest number is `5`.
- For the sub-array `[13, 27, 18, 26]`, the largest number is `27`.
- For the sub-array `[32, 35, 37, 39]`, the largest number is `39`.
- For the sub-array `[1000, 1001, 857, 1]`, the largest number is `1001`.

### Final Result:
The final result will be `[5, 27, 39, 1001]`.


### ANSWER

In [ ]:
def largestOfFour(arr):
    # Create a list to store the largest numbers
    largest_numbers = []
    
    # Iterate over each sub-array
    for sub_array in arr:
        # Find the largest number in the current sub-array
        largest_numbers.append(max(sub_array))
    
    # Return the list of largest numbers
    return largest_numbers

# Example Usage:
print(largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]))
# Output: [5, 27, 39, 1001]

print(largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]))
# Output: [9, 35, 97, 1000000]


[5, 27, 39, 1001]
[9, 35, 97, 1000000]


### Explanation of the Code:

- **max(sub_array)**: This function is used to find the maximum (largest) number in each sub-array.
- **append()**: Adds the largest number of the current sub-array to the result list `largest_numbers`.

After iterating through all the sub-arrays, the function returns a list containing the largest number from each sub-array.

### Output for the Examples:

1. `largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])` returns `[5, 27, 39, 1001]`.
2. `largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]])` returns `[9, 35, 97, 1000000]`.


### LongestDigitsPrefix

### Task

### Problem Description:

Given a string, output its longest prefix which contains only digits.

### Example:

For `inputString = "123aa1"`, the output should be:
```python
longestDigitsPrefix(inputString) = "123"
 Hints:
- `split()`
- `includes()`
- `push()`
- `join()`

 Input/Output:

- **Time Limit**: 4000ms (JavaScript)
- **Input**: A string `inputString` where `3 ≤ inputString.length ≤ 35`.
- **Output**: A string.


### Explanation:

The task is to find the longest prefix of a string that consists only of digits. A prefix is defined as the initial portion of the string. The goal is to extract the part of the string that starts from the beginning and contains only numeric characters (0-9).

### Steps to Solve:

1. Iterate through the characters of the input string.
2. As long as the character is a digit, keep adding it to the result.
3. Once you encounter a non-digit character, stop and return the collected digits as the result.
4. In case the string starts with no digits, the result will be an empty string.


### ANSWER

In [ ]:
def longestDigitsPrefix(inputString):
    # Initialize an empty result string
    result = ''
    
    # Iterate over each character in the inputString
    for char in inputString:
        # Check if the character is a digit
        if char.isdigit():
            result += char  # Append the digit to the result string
        else:
            break  # Stop if a non-digit character is encountered
    
    # Return the longest digits prefix
    return result

# Example usage:
print(longestDigitsPrefix("123aa1"))  # Output: "123"
print(longestDigitsPrefix("4567abc"))  # Output: "4567"
print(longestDigitsPrefix("abc123"))  # Output: ""


123
4567



### Explanation of the Code:

- **isdigit()**: This built-in string method checks whether a character is a digit (from 0 to 9). If it is, the character is added to the result string.
  
- **+=**: This operator is used to append the digit to the result string as we iterate through the input string.
  
- **break**: Once a non-digit character is encountered, the loop terminates as we no longer need to continue looking for the prefix of digits.

### Edge Case:
- If the input string starts with non-digits (e.g., "abc123"), the result will be an empty string, as no digits appear at the start.

### Output for the Examples:

- For `longestDigitsPrefix("123aa1")`, the output will be `"123"`.
- For `longestDigitsPrefix("4567abc")`, the output will be `"4567"`.
- For `longestDigitsPrefix("abc123")`, the output will be `""` (an empty string).


### MakeArrayConsecutive2

### Task

### Problem Description:

Ratiorg got statues of different sizes as a present from CodeMaster for his birthday, each statue having a non-negative integer size. Since he likes to make things perfect, he wants to arrange them from smallest to largest so that each statue will be bigger than the previous one exactly by 1. He may need some additional statues to be able to accomplish that. Help him figure out the minimum number of additional statues needed.

### Example:

For `statues = [6, 2, 3, 8]`, the output should be:
```python
makeArrayConsecutive2(statues) = 3
 Problem Description:

Ratiorg needs statues of sizes 4, 5, and 7.

 Hints:
- `sort()`
- `indexOf()`

 Input/Output:

- **Time Limit**: 4000ms (JavaScript)

- **Input**: An array of distinct non-negative integers `statues`.

- **Guaranteed Constraints**:
  - `1 ≤ statues.length ≤ 10`
  - `0 ≤ statues[i] ≤ 20`

- **Output**: An integer, the minimal number of statues that need to be added to the existing statues such that it contains every integer size from an interval `[L, R]` (for some `L, R`) and no other sizes.


### 🎯 Goal:
Given an array of distinct statue sizes (non-negative integers), determine how many statues are missing to make the sequence consecutive — i.e., every size from the smallest to the largest should appear, with no gaps.

### 🔧 How It Works:

1. **Find the smallest and largest values** in the array.
2. **Count how many numbers** should be in the full consecutive sequence (from smallest to largest, inclusive).
3. **Subtract the number of statues you already have** from the total count to get the number of missing statues.


### ANSWER

In [ ]:
def makeArrayConsecutive2(statues):
    min_size = min(statues)
    max_size = max(statues)
    
    # Total numbers expected in the consecutive sequence
    total_needed = max_size - min_size + 1
    
    # Subtract the number we already have
    return total_needed - len(statues)

# Example usage
print(makeArrayConsecutive2([6, 2, 3, 8]))  # Output: 3
print(makeArrayConsecutive2([0, 1, 3]))     # Output: 1 (missing 2)
print(makeArrayConsecutive2([5, 4, 6, 7]))  # Output: 0 (already consecutive)


3
1
0


### 🧠 Why It Works:

- `max(statues) - min(statues) + 1`: Gives the total count of numbers in the full consecutive sequence.
- `len(statues)`: Number of statues we already have.
- The **difference** tells how many statues are missing.

### 📌 Constraints Recap:

- `1 ≤ statues.length ≤ 10`
- `0 ≤ statues[i] ≤ 20`

So this simple approach is **efficient and safe**.


### MatrixElementsSum

### Task

### 🏢 Problem Description:

After becoming famous, CodeBots decided to move to a new building and live together. The building is represented by a rectangular matrix of rooms, each cell containing an integer — the price of the room.

Some rooms are free (their cost is 0), but that's probably because they are haunted 👻, so all the bots are afraid of them. That is why **any room that is free or is located anywhere below a free room in the same column is not considered suitable** for the bots.

Help the bots calculate the **total price of all the rooms** that are suitable for them.

---

### 📌 Example:

For:

```python
matrix = [
  [0, 1, 1, 2],
  [0, 5, 0, 0],
  [2, 0, 3, 3]
]
### 🧾 Output Example:

The output should be:

```python
matrixElementsSum(matrix) = 9

Thus, the answer is:  
**1 + 5 + 1 + 2 = 9**

---

### 💡 Hints:
- `push()`
- `indexOf()`

---

### 🔢 Input/Output:

- **Time Limit**: 4000ms (JavaScript)

#### Input:
A 2-dimensional array of integers `matrix`, representing a rectangular matrix of the building.

#### Guaranteed Constraints:
- `1 ≤ matrix.length ≤ 5`
- `1 ≤ matrix[i].length ≤ 5`
- `0 ≤ matrix[i][j] ≤ 10`

#### Output:
An integer — the total cost of suitable rooms.


### 🏢 Problem Explanation: `matrixElementsSum`

You are given a **2D matrix** where:

- Each number represents the **cost of a room**.

---

### ❌ A room is unsuitable if:
- It is **free** (has a value of `0`), **or**
- It is **below a free room in the same column**.

---

### ✅ Your task:
Sum the values of only the **suitable rooms** — that is, rooms that:
- Are not free,
- And are **not located beneath** a free room in their column.
### ✅ Example

**Input:**
```python
matrix = [
  [0, 1, 1, 2],
  [0, 5, 0, 0],
  [2, 0, 3, 3]
]
### ✅ Result: 9

Because the suitable rooms are:

### ✅ Suitable Rooms Matrix:

First row:   [x, 1, 1, 2]  
Second row:  [x, 5, x, x]  
Third row:   [x, x, x, x]

Where `x` marks the unsuitable rooms.

---

### 🔧 Strategy

- Traverse the matrix **column by column**.
- If a room is `0`, **mark that column as "haunted"** from that row downward.
- **Only add to the sum** if the column **has not been haunted yet**.


### ANSWER

In [ ]:
def matrixElementsSum(matrix):
    total = 0
    rows = len(matrix)
    cols = len(matrix[0])

    # Track haunted columns
    for col in range(cols):
        for row in range(rows):
            if matrix[row][col] == 0:
                break  # All rooms below are unsuitable
            total += matrix[row][col]

    return total

# Example usage:
matrix = [
    [0, 1, 1, 2],
    [0, 5, 0, 0],
    [2, 0, 3, 3]
]
print(matrixElementsSum(matrix))  # Output: 9


9


### 🧠 Why It Works:

- **Looping top-down** ensures that when we hit a `0`, we can **skip the rest of the column** below it, as all subsequent rooms in that column are unsuitable.
  
- The **time complexity** is small (<= 25 elements), so using **nested loops** is efficient.
